/* ==============================================
   THE LONG HAUL — package pickup + delivery + respawn + roll

   Four functions live here:
     rollPkg(destId, risky, forceLost)
                         — v0.0.8.1. Spawn roller. Rolls base
                           size \u2192 modifier \u2192 label filtered by
                           destination. Replaces world.js's
                           old NPC_PKGS/LOST_PKGS table-pick.
     scanForPickup()     — proximity pickup scan (runs every
                           walking/carrying tick). Also handles
                           sandalweed harvest.
     tryDeliver(nodeId)  — fires on node arrival. Most cross-
                           system function in the codebase \u2014
                           touches recovery, multiplayer, trust,
                           identification, render, and log.
     tickPkgRespawns()   — periodic (every 10 ticks) rescan
                           that un-picks packages whose
                           respawnIn has counted to zero.

   Package lifecycle:
     - Generated by world.js at startup (one pkg per eligible cell).
     - Picked up here → pkg.picked=true, copied into S.inventory
       with _worldCell backref.
     - Delivered here → normal pkgs get respawnIn=PKG_RESPAWN_TICKS;
       recovery pkgs one-shot (cell.pkg=null).

   Recovery metadata (isRecovery, recoveryFromPorter) rides the
   package from pickup → inventory → delivery; delivery broadcasts
   lost_recovered via postActivity.
   ============================================== */
'use strict';

import { S } from './state.js';
import * as C from './constants.js';
import { NPC_DEFS } from './data/npc-defs.js';
import {
  PKG_BASES, PKG_SIZE_WEIGHTS, PKG_SIZE_WEIGHTS_RISKY,
  PKG_MODIFIERS, PKG_LABELS_BY_SIZE, PKG_LOST_SCRIP_MULT,
  PKG_LABELS_BY_TERRAIN_ORIGIN,
} from './data/packages.js';
import { cellKeyFromCoords, snapInteriorCell } from './data/terrain.js';
import { placedGearAt } from './gear.js';
import { emit as tEmit, accum as tAccum } from './telemetry.js';
import { postActivity, shortPorterId, postLostDrop } from './multiplayer.js';
import { updatePorterStripBadges } from './recovery.js';
import { addTrust, computeTrustGain, speakDelivery, recordDelivery } from './trust.js';
import { getNodeStage, setNodeStage } from './identification.js';
import { sandalCap, renderBoots } from './boots.js';
import { addLog } from './render/log.js';
import { renderCourierStack, renderCargoSlots } from './render/hud.js';
import { drawRouteMap, courierXY, pointInRing } from './render/route-map.js';
import { renderSettlements } from './render/settlements.js';
import { weatherAtCourier } from './weather.js';
import { getDisplayLabel } from './identification.js';

// Local aliases — live references into S._transient. Never reassign these.
const els = S._transient.els;
const worldCells = S._transient.worldCells;

// v0.0.9.5.1 — delivery-broadcast throttle. Every porter delivers
// constantly and the feed was drowning in delivery events; gate to
// one broadcast per DELIVERY_BROADCAST_GATE_MS (10 minutes real-time).
// Session-local (no persistence) — first delivery after reload always
// fires, matching the "is anyone out there" signal on cold start.
const DELIVERY_BROADCAST_GATE_MS = 10 * 60 * 1000;
let lastDeliveryBroadcastTs = 0;

// v0.0.7.21 — sticky gun occupies one cargo slot unless holstered.
// Every pkg slot accounting goes through this helper so cargo
// cap math stays in one place. renderCargoSlots also reads this
// to paint the right slot count.
export function effectiveMaxSlots() {
  if (S.stickyGun && !S.stickyGun.holstered) return Math.max(0, S.maxSlots - 1);
  return S.maxSlots;
}

// v0.0.9.4.1 — shared tooltip formatter for pkg hover. Keeps the
// fieldstrip (ground pkgs) and cargo grid (carried pkgs) tooltips in
// lockstep. Multi-line (CSS `white-space: pre` on `.has-tooltip::after`
// renders the `\n` breaks). Format:
//   [size] label (modifier)
//   [recovery from PTR-XXXX]  |  [lost]         (if applicable)
//   → destination
//   Xc
export function formatPkgTooltip(pkg) {
  const modTag = pkg.modifier ? ` (${pkg.modifier})` : '';
  const lines = [`[${pkg.size}] ${pkg.label}${modTag}`];
  if (pkg.isRecovery && pkg.recoveryFromPorter) {
    lines.push(`[recovery from ${shortPorterId(pkg.recoveryFromPorter)}]`);
  } else if (pkg.isLost) {
    lines.push(`[lost]`);
  }
  lines.push(`\u2192 ${getDisplayLabel(pkg.destId)}`);
  lines.push(`${pkg.scrip}\u00a2`);
  return lines.join('\n');
}

// v0.0.9.4.1 — exported for the cursor-pickup path in world.js's
// fieldstrip click handler so both auto and manual pickup compute
// the same reach.
// Base C.PKG_PICKUP_RANGE when bare-handed; extended to
// C.STICKY_GUN_RANGE when gun is owned and has ammo. Holstering
// does NOT extend range — you can't shoot through the holster.
export function pickupRange() {
  let range;
  if (S.stickyGun && !S.stickyGun.holstered && S.stickyGun.ammo > 0) {
    range = C.STICKY_GUN_RANGE;
  } else {
    range = C.PKG_PICKUP_RANGE;
  }
  // v0.0.8 — downpour reduces visibility/reach
  if (weatherAtCourier().intensity === 'downpour') {
    range = Math.max(2, range - C.DOWNPOUR_RANGE_PENALTY);
  }
  return range;
}

// ============================================================
// PACKAGE ROLL (v0.0.8.1)
// ============================================================
// Weighted pick from a {key: weight} map. Returns a key.
function weightedKey(weights) {
  const keys = Object.keys(weights);
  const total = keys.reduce((s, k) => s + weights[k], 0);
  let r = Math.random() * total;
  for (const k of keys) { r -= weights[k]; if (r <= 0) return k; }
  return keys[0];
}

// Weighted pick from an array via a weight-getter fn. Returns the item.
function weightedArr(arr, getW) {
  const total = arr.reduce((s, x) => s + getW(x), 0);
  let r = Math.random() * total;
  for (const x of arr) { r -= getW(x); if (r <= 0) return x; }
  return arr[0];
}

// v0.0.9.4 — ring-distance-weighted destination picker. Replaces the
// old edge-endpoint default (`destId = S.edges[edgeIdx][1]`). Picks a
// clockwise offset 0..5 from the spawn edge's endpoint using the
// DEST_DIV_WEIGHTS curve (heavy forward bias, rare backwards), then
// walks the ring to the resulting node. Offset 0 = next shelter (same
// as the old default); offsets 1-3 build the medium-haul body; 4-5
// are effectively "backwards" and rare. Paired with v0.0.8.1's
// dest-tagged label pool, the spawn now reads as a diverse stream of
// "for whom" rather than "always the next shelter."
export function rollDestForSpawn(spawnEdgeIdx) {
  const offsets = C.DEST_DIV_WEIGHTS;
  const total = offsets.reduce((s, w) => s + w, 0);
  let r = Math.random() * total;
  let off = 0;
  for (let i = 0; i < offsets.length; i++) {
    r -= offsets[i];
    if (r <= 0) { off = i; break; }
  }
  const n = S.edges.length;
  return S.edges[(spawnEdgeIdx + off) % n][1];
}

// rollPkg — unified package spawn roll.
//
//   destId     — where the pkg is going (filters the label pool)
//   cellRisky  — risky cells bump xl spawn chance ~6x
//   forceLost  — when true, flags isLost + applies lost scrip mult.
//                Ambient world-spawn lost rolls through here today;
//                v0.0.8.2 recovery pipeline inversion will own all
//                isLost spawning.
//
// Returns a world-ready pkg object. Modifier effects (fragile damage
// branch, HUD badges, cargoStraps) are inert in v0.0.8.1 — the
// `modifier` field is set on the pkg but nothing reads it yet.
export function rollPkg(destId, cellRisky, forceLost) {
  // 1. Size roll. Risky cells use the bumped xl table.
  const sizeWeights = cellRisky ? PKG_SIZE_WEIGHTS_RISKY : PKG_SIZE_WEIGHTS;
  const size = weightedKey(sizeWeights);
  const base = PKG_BASES[size];

  // 2. Modifier roll (filtered by size incompatibility).
  const validMods = PKG_MODIFIERS.filter(m => !m.incompat || !m.incompat.includes(size));
  const mod = weightedArr(validMods, m => m.weight);

  // 3. Apply modifier deltas to the base.
  let kg    = base.kg;
  let slots = base.slots;
  let scrip = base.scrip;
  if (mod.id) {
    if (mod.kgDelta === 'halve')   kg = Math.max(1, Math.floor(kg / 2));
    if (mod.kgDelta === 'add1to3') kg = kg + 1 + Math.floor(Math.random() * 3);
    if (mod.slotDelta)             slots = slots + mod.slotDelta;
    if (mod.scripMult)             scrip = Math.floor(scrip * mod.scripMult);
  }

  // 4. Label — filter the size's flat list by dest inclusion.
  // Fallback: if no label matches (shouldn't happen with the current
  // pool but defensive), use a generic placeholder.
  const candidates = (PKG_LABELS_BY_SIZE[size] || []).filter(l => l.dests.includes(destId));
  const label = candidates.length > 0
    ? candidates[Math.floor(Math.random() * candidates.length)].label
    : 'unmarked cargo';

  // 5. Lost flag + scrip bonus.
  if (forceLost) scrip = Math.floor(scrip * PKG_LOST_SCRIP_MULT);

  return {
    size, label, kg, slots, scrip,
    modifier: mod.id || null,
    isLost: !!forceLost,
    destId,
    picked: false,
    respawnIn: 0,
  };
}

// v0.0.9.6 commit 5 — interior pkg roller. Cell-native variant of
// rollPkg that pulls labels from PKG_LABELS_BY_TERRAIN_ORIGIN and
// applies per-terrain reward biases:
//   plateau    — normal roll, labels tagged mesa-salvage
//   mountain   — xl bias 4x + scrip x1.3 (reward for harsh terrain)
//   rockyHills — modifier-rate bump (fragile/heavy more common)
// destId still uses the standard DEST_DIV_WEIGHTS curve seeded on a
// "virtual edge" derived from the cell's position (nearest ring
// node's edge). Result: plateau pkgs near xi naturally route to near-
// start NPCs via forward-bias; mountain pkgs near pi similarly route
// SW-locals.
export function rollInteriorPkg(terrainOrigin, cellX, cellY) {
  // 1. Size roll with per-terrain bias.
  let sizeWeights = { ...PKG_SIZE_WEIGHTS };
  if (terrainOrigin === 'mountain') {
    sizeWeights.xl = (sizeWeights.xl || 1) * C.INTERIOR_MOUNTAIN_XL_BIAS;
  }
  const size = weightedKey(sizeWeights);
  const base = PKG_BASES[size];

  // 2. Modifier roll (with rockyHills bump).
  let mods = PKG_MODIFIERS.filter(m => !m.incompat || !m.incompat.includes(size));
  if (terrainOrigin === 'rockyHills') {
    // Bump non-null modifier weights by INTERIOR_ROCKYHILLS_MOD_BIAS
    mods = mods.map(m => m.id
      ? { ...m, weight: m.weight * C.INTERIOR_ROCKYHILLS_MOD_BIAS }
      : m);
  }
  const mod = weightedArr(mods, m => m.weight);

  // 3. Apply modifier deltas to the base.
  let kg    = base.kg;
  let slots = base.slots;
  let scrip = base.scrip;
  if (mod.id) {
    if (mod.kgDelta === 'halve')   kg = Math.max(1, Math.floor(kg / 2));
    if (mod.kgDelta === 'add1to3') kg = kg + 1 + Math.floor(Math.random() * 3);
    if (mod.slotDelta)             slots = slots + mod.slotDelta;
    if (mod.scripMult)             scrip = Math.floor(scrip * mod.scripMult);
  }

  // 4. Mountain scrip reward bump (reward for traversal cost).
  if (terrainOrigin === 'mountain') {
    scrip = Math.floor(scrip * C.INTERIOR_MOUNTAIN_SCRIP_MULT);
  }

  // 5. Destination — use cell's nearest-edge as the virtual origin
  // so DEST_DIV_WEIGHTS forward-bias routes cashable near-cell dests.
  const nearestEdgeIdx = nearestEdgeToPoint(cellX, cellY);
  const destId = rollDestForSpawn(nearestEdgeIdx);

  // 6. Label — terrain-origin pool, size-tier bucket. Filter by dest.
  const pool = (PKG_LABELS_BY_TERRAIN_ORIGIN[terrainOrigin] || {})[size] || [];
  const candidates = pool.filter(l => l.dests.includes(destId));
  const label = candidates.length > 0
    ? candidates[Math.floor(Math.random() * candidates.length)].label
    : 'salvaged cargo';

  return {
    size, label, kg, slots, scrip,
    modifier: mod.id || null,
    isLost: false,
    destId,
    terrainOrigin,  // v0.0.9.6 commit 5 — propagates through pickup/delivery
    picked: false,
    respawnIn: 0,
  };
}

// Find the ring edge index whose endpoint is geometrically closest
// to a given interior point. Used by rollInteriorPkg so the dest-
// weight curve has a sensible "from" to walk forward from.
function nearestEdgeToPoint(x, y) {
  let bestIdx = 0;
  let bestD = Infinity;
  for (let i = 0; i < S.edges.length; i++) {
    const [, toId] = S.edges[i];
    const node = S.routeNodes.find(n => n.id === toId);
    if (!node) continue;
    const d = (node.x - x) * (node.x - x) + (node.y - y) * (node.y - y);
    if (d < bestD) { bestD = d; bestIdx = i; }
  }
  return bestIdx;
}

// v0.0.9.6 commit 5 — seed interior pkgs at world-init. Iterates the
// drawInterior cell grid (12-unit step) inside the ring polygon,
// classifies each cell, rolls per-terrain spawn chance, and populates
// S.interiorPkgs keyed by cell position. Idempotent — re-running on
// a populated table is a no-op unless cell has no entry.
export function seedInteriorPkgs() {
  // Lazy-imported to avoid cycle — terrain.js doesn't need packages.js.
  // Late dynamic import is fine at seed time (runs once, not hot path).
  return import('./data/terrain.js').then(({ terrainAt }) => {
    const SPAWN_RATES = {
      plateau:    C.INTERIOR_SPAWN_PLATEAU,
      mountain:   C.INTERIOR_SPAWN_MOUNTAIN,
      rockyHills: C.INTERIOR_SPAWN_ROCKYHILLS,
    };
    if (!S.interiorPkgs) S.interiorPkgs = {};
    for (let yy = 50; yy <= 350; yy += 12) {
      for (let xx = 50; xx <= 350; xx += 12) {
        // Only seed cells that are actually inside the ring polygon;
        // terrainAt() classifies by distance from NPC anchors which
        // can leak slightly outside the crossable area (e.g. plateau
        // circle extending past xi's corner).
        if (!pointInRing(xx, yy)) continue;
        const key = cellKeyFromCoords(xx, yy);
        if (S.interiorPkgs[key]) continue;  // already seeded
        const terr = terrainAt(xx, yy);
        const rate = SPAWN_RATES[terr];
        if (!rate) continue;
        if (Math.random() >= rate) continue;
        const snapped = snapInteriorCell(xx, yy);
        const pkg = rollInteriorPkg(terr, snapped.x, snapped.y);
        S.interiorPkgs[key] = {
          x: snapped.x, y: snapped.y,
          terrainOrigin: terr,
          pkg,
          respawnIn: 0,
          picked: false,
        };
      }
    }
  });
}

// v0.0.9.4 — NPC outbound dispatch. On arrival at an NPC node, that NPC
// may offer a package destined for another node. Trust-scaled offer
// chance, per-visit cooldown. Uses the v0.0.8.1 dests[] tagging as a
// story-compatibility set — labels where originNodeId ∈ dests are part
// of that NPC's vocabulary; destination is any OTHER node in the
// label's dests, weighted by the same ring-distance curve as world-
// spawn (near > far > backwards).
export function tryOutboundDispatch(originNodeId) {
  if (!NPC_DEFS[originNodeId]) return;
  const npc = S.npcs[originNodeId];
  if (!npc || npc.trust < C.OUTBOUND_MIN_TRUST) return;

  // Per-visit guard: if we already handled an offer roll this arrival
  // (either offered or skipped), don't re-roll. outboundLastVisit is
  // reset when a DIFFERENT NPC is visited — see the !== check below.
  if (S._transient.outboundLastVisit === originNodeId) return;
  S._transient.outboundLastVisit = originNodeId;

  // Clear any stale pending offer from a previous NPC visit — the old
  // log button resolves to `if (!pending) return` when clicked.
  if (S._transient.outboundOfferPending &&
      S._transient.outboundOfferPending.originNodeId !== originNodeId) {
    S._transient.outboundOfferPending = null;
  }

  // Offer chance scales with trust, capped by OUTBOUND_BASE_RATE.
  const chance = Math.min(C.OUTBOUND_BASE_RATE, C.OUTBOUND_BASE_RATE * (npc.trust / 100));
  if (Math.random() >= chance) return;

  // Size roll (no risky-cell bump — arrival cells aren't "risky").
  const size = weightedKey(PKG_SIZE_WEIGHTS);

  // Filter labels: origin ∈ dests AND ≥2 dests (need somewhere to send).
  const candidates = (PKG_LABELS_BY_SIZE[size] || []).filter(
    l => l.dests.includes(originNodeId) && l.dests.length >= 2
  );
  if (candidates.length === 0) return;
  const chosen = candidates[Math.floor(Math.random() * candidates.length)];

  // Destination — pick from chosen.dests minus origin, weighted by
  // ring-distance curve (index into DEST_DIV_WEIGHTS by clockwise
  // offset from origin).
  const originEdgeIdx = S.edges.findIndex(e => e[0] === originNodeId);
  if (originEdgeIdx < 0) return; // defensive
  const ringLen = S.edges.length;
  const otherDests = chosen.dests.filter(d => d !== originNodeId);
  if (otherDests.length === 0) return;
  const weighted = otherDests.map(d => {
    let off = -1;
    for (let i = 0; i < ringLen; i++) {
      if (S.edges[(originEdgeIdx + i) % ringLen][1] === d) { off = i; break; }
    }
    return { dest: d, weight: (off >= 0 ? C.DEST_DIV_WEIGHTS[off] : 1) || 1 };
  });
  const totalW = weighted.reduce((s, w) => s + w.weight, 0);
  let r = Math.random() * totalW;
  let destId = weighted[0].dest;
  for (const w of weighted) {
    r -= w.weight;
    if (r <= 0) { destId = w.dest; break; }
  }

  // Build the pkg. Size + label are fixed (our chosen), but modifier,
  // kg/slots/scrip get re-rolled via the same PKG_BASES + PKG_MODIFIERS
  // machinery as rollPkg so the pkg is internally consistent.
  const base = PKG_BASES[size];
  const validMods = PKG_MODIFIERS.filter(m => !m.incompat || !m.incompat.includes(size));
  const mod = weightedArr(validMods, m => m.weight);
  let kg = base.kg, slots = base.slots, scrip = base.scrip;
  if (mod.id) {
    if (mod.kgDelta === 'halve')   kg = Math.max(1, Math.floor(kg / 2));
    if (mod.kgDelta === 'add1to3') kg = kg + 1 + Math.floor(Math.random() * 3);
    if (mod.slotDelta)             slots = slots + mod.slotDelta;
    if (mod.scripMult)             scrip = Math.floor(scrip * mod.scripMult);
  }

  const pkg = {
    size, label: chosen.label, kg, slots, scrip,
    modifier: mod.id || null,
    isLost: false,
    destId,
    picked: false,
    respawnIn: 0,
    outboundFrom: originNodeId,    // v0.0.9.4 — flags delivery bonus
  };

  // v0.0.9.5.2 — auto-pickup instead of prompt. Idle-first: never ask
  // the player to click a log button mid-route. If there's cargo room
  // the pkg goes straight to inventory with a trust bump; if not, the
  // outboundLastVisit guard above already blocks re-rolls THIS visit,
  // and coming back to this NPC later re-rolls (may offer a different
  // pkg — that's fine, "no worries" per design intent).
  if (pkg.slots > effectiveMaxSlots() - S.usedSlots) return;
  if (pkg.kg   > S.maxWeight - S.usedWeight)         return;

  const carried = {
    size: pkg.size, label: pkg.label, kg: pkg.kg, slots: pkg.slots,
    scrip: pkg.scrip, isLost: false, destId: pkg.destId,
    modifier: pkg.modifier || null,
    isRecovery: false,
    recoveryFromPorter: null,
    outboundFrom: originNodeId,    // carries through to tryDeliver
    _worldCell: undefined,          // no world cell — dispatched, not picked up
  };
  S.inventory.push(carried);
  S.usedSlots  += carried.slots;
  S.usedWeight += carried.kg;
  S.status = 'carrying';
  renderCourierStack();
  renderCargoSlots(true);

  // +N trust at origin for accepting. Same weight-scaled formula as
  // delivery; +1 bonus does NOT apply here (that's the dest-side bonus).
  const callsign  = NPC_DEFS[originNodeId].callsign;
  const destSettle = S.settlements[destId];
  const destLabel  = destSettle ? destSettle.label : destId;
  const originGain = 1 + Math.floor(pkg.slots / 2);
  addTrust(originNodeId, originGain, 'outbound-accept');
  addLog(
    `picked up <span class="log-hi">[${size}] ${chosen.label}</span> ` +
    `from <span class="log-hi">${callsign}</span> for <span class="log-hi">${destLabel}</span> ` +
    `\u2014 <span class="log-ok">+${Math.round(originGain)} trust</span>`
  );
}

// ============================================================
// PACKAGE PICKUP
// ============================================================
// v0.0.9.4.1 — shared pickup-acceptance body. Both the auto-pickup
// scan (scanForPickup) and the cursor-pickup click handler
// (tryCursorPickup) funnel here. Returns true on success, false on
// failure (slots/weight short — logs the "can't lift" line once via
// the dedupe key). offset is the distance-from-courier; used to
// decide whether the sticky-gun spent ammo (cross-range pick).
function acceptPickup(ci, offset) {
  const cell = worldCells[ci];
  if (!cell || !cell.pkg || cell.pkg.picked) return false;
  const pkg = cell.pkg;
  const slotsShort  = pkg.slots > effectiveMaxSlots() - S.usedSlots;
  const weightShort = pkg.kg    > S.maxWeight - S.usedWeight;
  if (slotsShort || weightShort) {
    // v0.0.9.5.1 — pickup-fail dedupe keyed by cargo state ONLY (was
    // ci:usedSlots:usedWeight). Old key alternated between two heavy
    // pkgs in range every tick because the scan loop hits them in
    // order and each updates lastPickupFailKey, so neither hit its
    // own key on the next pass. New key fires once per cargo state,
    // re-fires after drop/deliver. Callsite unchanged.
    const key = `${S.usedSlots}:${S.usedWeight}`;
    if (S._transient.lastPickupFailKey !== key) {
      S._transient.lastPickupFailKey = key;
      const reason = slotsShort ? 'no cargo slots' : 'too heavy';
      addLog(`<span class="log-wn">can't lift</span> [${pkg.size}] ${pkg.label} \u2014 ${reason}`);
    }
    return false;
  }

  pkg.picked = true;
  // v0.0.7.21 — sticky gun ammo decrement. Only on cross-range picks:
  // if offset > C.PKG_PICKUP_RANGE, the gun reached past bare-hand
  // range and a shot was spent. Offsets within bare-hand range don't
  // consume ammo (courier just walked up to it).
  if (S.stickyGun && !S.stickyGun.holstered && offset > C.PKG_PICKUP_RANGE && S.stickyGun.ammo > 0) {
    S.stickyGun.ammo--;
  }
  const carried = {
    size: pkg.size, label: pkg.label, kg: pkg.kg, slots: pkg.slots,
    scrip: pkg.scrip, isLost: pkg.isLost, destId: pkg.destId,
    modifier: pkg.modifier || null,
    isRecovery: !!pkg.isRecovery,
    recoveryFromPorter: pkg.recoveryFromPorter || null,
    _worldCell: ci,
  };
  S.inventory.push(carried);
  S.usedSlots  += carried.slots;
  S.usedWeight += carried.kg;
  S.status = 'carrying';
  renderCourierStack();
  renderCargoSlots(true);
  if (els.courierAt) els.courierAt.className = 'tlh-at bounce carry';
  const lostTag = carried.isRecovery
    ? ` <span class="log-wn">[recovery]</span> from <span class="log-hi">${shortPorterId(carried.recoveryFromPorter)}</span>`
    : (carried.isLost ? ' <span class="log-wn">[lost pkg]</span>' : '');
  addLog(`picked up <span class="log-hi">[${carried.size}] ${carried.label}</span>${lostTag}`);
  return true;
}

// v0.0.9.6 commit 5 — interior pkg pickup. Plateau pkgs gate on a
// placed ladder at the same cell (tutorial: gear unlocks elevated
// rewards); mountain + rocky-hills pkgs pick up freely per idle-
// first. Propagates terrainOrigin into the inventory entry so
// delivery logic can flavor accordingly.
function acceptInteriorPickup(entry) {
  if (!entry || entry.picked) return false;
  const pkg = entry.pkg;
  if (!pkg) return false;
  // Plateau gate — require a placed ladder at the same snapped cell.
  // Throttle uses a segment-scoped flag so the gate message fires
  // once per shortcut, not on every tick. Resets on segment change
  // via resetGearLogThrottles() in gear.js.
  if (entry.terrainOrigin === 'plateau' && !placedGearAt(entry.x, entry.y)) {
    tEmit('pickup.failed', { reason: 'plateau_gate' });
    if (!S._transient.plateauGateLogged) {
      S._transient.plateauGateLogged = true;
      addLog('<span class="log-wn">plateau top out of reach</span> \u2014 a ladder would do it');
    }
    return false;
  }
  const slotsShort  = pkg.slots > effectiveMaxSlots() - S.usedSlots;
  const weightShort = pkg.kg    > S.maxWeight - S.usedWeight;
  if (slotsShort || weightShort) {
    const key = `${S.usedSlots}:${S.usedWeight}`;
    if (S._transient.lastPickupFailKey !== key) {
      S._transient.lastPickupFailKey = key;
      const reason = slotsShort ? 'no cargo slots' : 'too heavy';
      addLog(`<span class="log-wn">can't lift</span> [${pkg.size}] ${pkg.label} \u2014 ${reason}`);
    }
    return false;
  }
  entry.picked = true;
  tEmit('pkg.picked', { size: pkg.size, terrainOrigin: entry.terrainOrigin });
  const carried = {
    size: pkg.size, label: pkg.label, kg: pkg.kg, slots: pkg.slots,
    scrip: pkg.scrip, isLost: pkg.isLost, destId: pkg.destId,
    modifier: pkg.modifier || null,
    terrainOrigin: entry.terrainOrigin,
    _interiorKey: cellKeyFromCoords(entry.x, entry.y),
  };
  S.inventory.push(carried);
  S.usedSlots  += carried.slots;
  S.usedWeight += carried.kg;
  S.status = 'carrying';
  renderCourierStack();
  renderCargoSlots(true);
  if (els.courierAt) els.courierAt.className = 'tlh-at bounce carry';
  addLog(`picked up <span class="log-hi">[${carried.size}] ${carried.label}</span> <span class="log-dim">[${entry.terrainOrigin}]</span>`);
  return true;
}

// v0.0.9.6 commit 5 — interior pickup scan. Iterates S.interiorPkgs
// for any entry within PKG_PICKUP_RANGE cells (viewBox-unit distance)
// of the courier's current position. Fires before ring scan so
// interior pickups don't get blocked by ring-cell iteration.
function scanInteriorPickups() {
  const seg = S._transient.currentSegment;
  if (!seg || (seg.type !== 'shortcut' && seg.type !== 'river-drift')) return false;
  const here = courierXY();
  if (!here) return false;
  if (!S.autoGrab) return false;  // auto-grab toggle respects commit 4 parity
  // Pickup radius in SVG units: PKG_PICKUP_RANGE cells * 12 u/cell.
  const rangeSvg = C.PKG_PICKUP_RANGE * 12;
  const table = S.interiorPkgs || {};
  for (const key of Object.keys(table)) {
    const entry = table[key];
    if (!entry || entry.picked) continue;
    const d = Math.hypot(entry.x - here.x, entry.y - here.y);
    if (d > rangeSvg) continue;
    if (acceptInteriorPickup(entry)) return true;
  }
  return false;
}

export function scanForPickup() {
  if (S.status !== 'walking' && S.status !== 'carrying') return;
  // v0.0.9.6 commit 5 — interior pickup first (takes priority when on
  // shortcut / river-drift segment; no-op on ring).
  if (scanInteriorPickups()) return;
  const courierCell = Math.floor((S.edgeIdx * C.CELLS_PER_EDGE) + (S.dotT * C.CELLS_PER_EDGE));
  const range = pickupRange();
  for (let offset = 0; offset <= range; offset++) {
    const ci   = (courierCell + offset) % C.TOTAL_CELLS;
    const cell = worldCells[ci];
    if (!cell) continue;

    // Sandalweed auto-harvest always runs (it's not pkg pickup —
    // not gated by S.autoGrab). v0.0.9.4.1: player's "grab: off"
    // toggle targets packages specifically.
    if (cell.sandal) {
      if (S.sandalweedCount >= sandalCap()) continue;
      cell.sandal = false;
      cell.html = `<span class="fc fc-fl">   </span>`;
      S.sandalweedCount++;
      addLog(`harvested <span class="log-hi">sandalweed</span> (${S.sandalweedCount}/${sandalCap()})`);
      renderBoots();
      continue;
    }

    if (!cell.pkg || cell.pkg.picked) continue;
    // v0.0.9.4.1 — auto-pickup gated. Cursor path (tryCursorPickup)
    // remains available even when autoGrab is off.
    if (!S.autoGrab) continue;
    // v0.0.9.4.1 — toss-cooldown: skip pkgs we just dropped so they
    // don't get re-grabbed by auto. Cursor pickup still works on them.
    if (cell.pkg.tossedUntilTick && S.ticks < cell.pkg.tossedUntilTick) continue;
    if (acceptPickup(ci, offset)) return;
  }
}

// v0.0.9.4.1 — cursor-driven manual pickup. Called from the fieldstrip
// click handler bound in world.js. Verifies the clicked cell is
// within current pickupRange() (defensive — the in-range class on
// the span could lag one tick), then routes through acceptPickup.
// Return value unused by callers; exists for parity w/ scan path.
//
// Cursor pickup is bidirectional — unlike auto-scan which only looks
// forward, clicking works for pkgs behind the courier too. Lets the
// player reclaim a just-tossed pkg that landed at a -1/-2/-3 fallback
// cell in ejectFromCargo's offset search.
//
// Cursor pickup also BYPASSES the toss-cooldown (tossedUntilTick) —
// a click is an explicit choice; the cooldown only exists to stop
// auto-scan from instant-regrabbing. acceptPickup doesn't check the
// cooldown at all, so calling it directly from here is the bypass.
export function tryCursorPickup(ci) {
  if (S.status !== 'walking' && S.status !== 'carrying') return false;
  const courierCell = Math.floor((S.edgeIdx * C.CELLS_PER_EDGE) + (S.dotT * C.CELLS_PER_EDGE));
  const range = pickupRange();
  // Ring-wrapped bidirectional distance: shorter of forward + backward
  // arcs from courierCell to ci.
  const raw      = (ci - courierCell + C.TOTAL_CELLS) % C.TOTAL_CELLS;
  const distance = Math.min(raw, C.TOTAL_CELLS - raw);
  if (distance > range) return false;
  // Pass the absolute distance as `offset` so acceptPickup's sticky-gun
  // ammo threshold (offset > PKG_PICKUP_RANGE = cross-range shot)
  // works uniformly for forward + backward clicks.
  return acceptPickup(ci, distance);
}

// v0.0.9.4.1 commit 2 — eject a cargo item via drag-to-toss. Called
// from the drag layer (render/drag.js) when a cargo drag releases
// outside the cargo-grid bounding box.
//
// Lost chance is modifier-scaled — fragile/lightweight pkgs scatter
// more often (they catch wind, they shatter on landing); heavy pkgs
// land where you throw them. Base 10% for no-modifier pkgs.
//
//   kept branch  → pkg drops at the courier's current cell (walks ±3
//                  cells looking for an empty pkg slot; if nothing
//                  empty in that window, escalates to lost — "the
//                  trail's too dense to set it down"). Becomes a
//                  normal world pkg; cursor/auto pickup will grab it
//                  again normally.
//   lost branch  → pkg enters the multiplayer recovery pipeline via
//                  postLostDrop, tagged with this player's porter ID.
//                  Other porters can recover it. Vanishes locally.
const OUTBOUND_LOST_CHANCE = {
  fragile:     0.30,
  unwieldy:    0.25,
  lightweight: 0.20,
  heavy:       0.05,
};
const OUTBOUND_LOST_BASE = 0.10;

export function ejectFromCargo(invIdx) {
  const pkg = S.inventory[invIdx];
  if (!pkg) return;

  const chance = pkg.modifier && (pkg.modifier in OUTBOUND_LOST_CHANCE)
    ? OUTBOUND_LOST_CHANCE[pkg.modifier]
    : OUTBOUND_LOST_BASE;
  const lostRoll = Math.random() < chance;

  // Try to find a world cell to drop into (for the kept branch, or
  // as a fallback if we escalate to lost).
  const courierCell = Math.floor((S.edgeIdx * C.CELLS_PER_EDGE) + (S.dotT * C.CELLS_PER_EDGE));
  let dropCi = -1;
  // Candidates: current cell, then ±1, ±2, ±3 (outward).
  const offsets = [0, 1, -1, 2, -2, 3, -3];
  for (const off of offsets) {
    const ci = (courierCell + off + C.TOTAL_CELLS) % C.TOTAL_CELLS;
    const cell = worldCells[ci];
    if (cell && !cell.pkg && !cell.sandal) { dropCi = ci; break; }
  }

  // Escalate kept → lost if no drop cell found in the ±3 window.
  const forcedLost = dropCi < 0;
  const wentLost = lostRoll || forcedLost;

  // Remove from inventory first (so all paths share the removal logic).
  S.inventory.splice(invIdx, 1);
  S.usedSlots  = Math.max(0, S.usedSlots - pkg.slots);
  S.usedWeight = Math.max(0, S.usedWeight - pkg.kg);

  if (wentLost) {
    // Broadcast to the recovery pipeline (tags with porter id inside
    // postLostDrop via getCachedPorterId).
    const lostPkg = { ...pkg, isLost: true };
    postLostDrop(lostPkg);
    const reason = forcedLost ? 'trail too crowded' : 'scattered on the toss';
    addLog(`<span class="log-wn">lost</span> [${pkg.size}] ${pkg.label} \u2014 ${reason}`);
  } else {
    // Drop to world cell. Build a fresh pkg shape matching what
    // rollPkg produces so auto/cursor pickup works normally.
    const dropped = {
      size: pkg.size, label: pkg.label, kg: pkg.kg, slots: pkg.slots,
      scrip: pkg.scrip,
      modifier: pkg.modifier || null,
      isLost: !!pkg.isLost,
      destId: pkg.destId,
      isRecovery: !!pkg.isRecovery,
      recoveryFromPorter: pkg.recoveryFromPorter || null,
      outboundFrom: pkg.outboundFrom,  // preserve outbound-dispatch flag
      picked: false,
      respawnIn: 0,
      // Auto-pickup cooldown so the pkg you just dropped doesn't get
      // instantly re-picked by the next tick's scanForPickup. Cursor
      // pickup ignores this — deliberate click is always honored.
      tossedUntilTick: S.ticks + C.TOSS_COOLDOWN_TICKS,
    };
    worldCells[dropCi].pkg = dropped;
    addLog(`tossed <span class="log-hi">[${pkg.size}] ${pkg.label}</span> onto the trail`);
    postActivity('toss', { label: pkg.label, size: pkg.size });
  }

  if (S.inventory.length === 0) {
    S.status = 'walking';
    if (els.courierAt) els.courierAt.className = 'tlh-at bounce';
  }
  renderCourierStack();
  renderCargoSlots(true);
}

// ============================================================
// PACKAGE DELIVERY
// ============================================================
export function tryDeliver(arrivedNodeId) {
  // v0.0.7.21 — sticky gun ammo refill at H, regardless of whether
  // there's a pkg to deliver. Home = rearm station.
  if (arrivedNodeId === 'H' && S.stickyGun && S.stickyGun.ammo < S.stickyGun.ammoMax) {
    const refilled = S.stickyGun.ammoMax - S.stickyGun.ammo;
    S.stickyGun.ammo = S.stickyGun.ammoMax;
    addLog(`<span class="log-ok">sticky gun</span> refilled \u2014 +${refilled} shots`);
  }

  const toDeliver = S.inventory.filter(p => p.destId === arrivedNodeId);
  if (toDeliver.length === 0) return;
  const settle = S.settlements[arrivedNodeId];
  const destLabel = settle ? settle.label : arrivedNodeId;
  toDeliver.forEach(pkg => {
    // v0.0.9.6.9 sim telemetry
    tEmit('pkg.delivered', { npc: arrivedNodeId, size: pkg.size, scrip: pkg.scrip, terrainOrigin: pkg.terrainOrigin || 'ring' });
    tAccum('pkg.delivered', 'scrip', pkg.scrip);
    tAccum('pkg.delivered', 'scrip_' + arrivedNodeId, pkg.scrip);
    tAccum('pkg.delivered', 'count_' + (pkg.terrainOrigin || 'ring'), 1);
    S.scrip      += pkg.scrip;
    S.delivered  += 1;
    S.usedSlots  -= pkg.slots;
    S.usedWeight -= pkg.kg;
    S.inventory.splice(S.inventory.indexOf(pkg), 1);
    if (pkg._worldCell !== undefined && worldCells[pkg._worldCell] && worldCells[pkg._worldCell].pkg) {
      if (pkg.isRecovery) {
        worldCells[pkg._worldCell].pkg = null;
        worldCells[pkg._worldCell].isRecovery = false;
        S.activeRecoveryCount = Math.max(0, S.activeRecoveryCount - 1);
        updatePorterStripBadges();
      } else {
        // v0.0.8.6: scavenger's eye reduces respawn by 20%
        worldCells[pkg._worldCell].pkg.respawnIn = S.upgrades.scavengerEye
          ? Math.floor(C.PKG_RESPAWN_TICKS * 0.8)
          : C.PKG_RESPAWN_TICKS;
      }
    }
    // v0.0.9.6 commit 5 — interior pkg respawn on delivery. Mirrors
    // the ring pattern; scavengerEye applies the same 20% reduction.
    if (pkg._interiorKey && S.interiorPkgs && S.interiorPkgs[pkg._interiorKey]) {
      const entry = S.interiorPkgs[pkg._interiorKey];
      entry.respawnIn = S.upgrades.scavengerEye
        ? Math.floor(C.INTERIOR_RESPAWN_TICKS * 0.8)
        : C.INTERIOR_RESPAWN_TICKS;
    }
    if (settle) { settle.supply = Math.min(100, settle.supply + 3); settle.rebuild = Math.min(100, settle.rebuild + 1); }
    const node = S.routeNodes.find(n => n.id === arrivedNodeId);
    if (node && getNodeStage(arrivedNodeId) < 3) {
      setNodeStage(arrivedNodeId, 3);
      addLog(`discovered: <span class="log-hi">${node.label}</span>`);
      drawRouteMap();
      renderSettlements();
      postActivity('discovery', { nodeId: arrivedNodeId, label: node.label });
      if (NPC_DEFS[arrivedNodeId]) {
        addTrust(arrivedNodeId, C.TRUST_GAIN_DISCOVERY, 'discovery');
      }
    }
    // v0.0.8.5: compute trust gain before logging so we can surface it.
    // Weight-scaled base (1 + floor(slots/2)) with profile multipliers.
    // v0.0.9.4: outbound-flagged pkgs get +OUTBOUND_BONUS_TRUST at dest
    // for being a relationship-spanning delivery (origin NPC already
    // awarded their own trust on accept).
    const gain  = NPC_DEFS[arrivedNodeId] ? computeTrustGain(pkg, arrivedNodeId) : 0;
    const bonus = pkg.outboundFrom && NPC_DEFS[arrivedNodeId] ? C.OUTBOUND_BONUS_TRUST : 0;
    const totalGain = gain + bonus;
    const trustSuffix = totalGain > 0 ? ` +${Math.round(totalGain)} trust` : '';
    const outboundTag = pkg.outboundFrom
      ? ` <span class="log-hi">[from ${NPC_DEFS[pkg.outboundFrom] ? NPC_DEFS[pkg.outboundFrom].callsign : pkg.outboundFrom}]</span>`
      : '';
    addLog(`delivered <span class="log-hi">[${pkg.size}] ${pkg.label}</span>${outboundTag} to <span class="log-hi">${destLabel}</span> \u2014 <span class="log-ok">+${pkg.scrip}\u00a2${trustSuffix}</span>`);
    // v0.0.9.5.1 — delivery broadcasts were the single largest feed
    // contributor (every porter delivers constantly). Throttled to
    // one broadcast per porter per DELIVERY_BROADCAST_GATE_MS so the
    // signal survives but the volume drops ~10-20x. Wall-clock gate
    // (session-local; first delivery after reload always fires).
    const nowTs = Date.now();
    if (nowTs - lastDeliveryBroadcastTs >= DELIVERY_BROADCAST_GATE_MS) {
      lastDeliveryBroadcastTs = nowTs;
      postActivity('delivery', { destId: arrivedNodeId, destLabel, scrip: pkg.scrip, size: pkg.size });
    }

    if (pkg.isRecovery && pkg.recoveryFromPorter) {
      postActivity('lost_recovered', {
        label: pkg.label,
        size: pkg.size,
        forPorter: pkg.recoveryFromPorter,
      });
      addLog(`<span class="log-ok">recovered</span> <span class="log-hi">${pkg.label}</span> \u2014 left by <span class="log-hi">${shortPorterId(pkg.recoveryFromPorter)}</span>`);
    }

    if (totalGain > 0) {
      const reason = pkg.outboundFrom
        ? 'outbound-delivery'
        : (pkg.isLost ? 'lost-delivery' : 'delivery');
      addTrust(arrivedNodeId, totalGain, reason);
    }
  });
  // v0.0.9.5 (commit 2): per-batch state update for stateful trust
  // profiles (tau homecoming km snapshot, iota wetland-tick reset,
  // delta routine-counter accrue/reset). Fires once per batch so a
  // multi-pkg delivery to a non-delta NPC counts as a single "visit"
  // for delta's routine profile. Safe to call before addTrust reads
  // — computeTrustGain already ran earlier in the loop.
  if (NPC_DEFS[arrivedNodeId]) recordDelivery(arrivedNodeId);
  // v0.0.8.4: NPC reacts to the delivery — one line per batch, picking
  // the most interesting condition (lost > damaged > fragile > heavy > normal).
  speakDelivery(arrivedNodeId, toDeliver);
  renderCourierStack();
  renderCargoSlots(true);
  if (S.inventory.length === 0) {
    S.status = 'walking';
    if (els.courierAt) els.courierAt.className = 'tlh-at bounce';
  }
  renderSettlements();
}

export function tickPkgRespawns() {
  for (let i = 0; i < C.TOTAL_CELLS; i++) {
    const cell = worldCells[i];
    if (!cell || !cell.pkg || !cell.pkg.picked || cell.pkg.respawnIn <= 0) continue;
    cell.pkg.respawnIn--;
    if (cell.pkg.respawnIn === 0) {
      const active = worldCells.filter(c => c.edgeIdx === cell.edgeIdx && c.pkg && !c.pkg.picked).length;
      if (active < C.PKG_MAX_PER_EDGE) {
        cell.pkg.picked = false;
        addLog(`<span class="log-ok">new package</span> spotted on the road`);
      } else {
        cell.pkg.respawnIn = C.PKG_RESPAWN_TICKS;
      }
    }
  }
  // v0.0.9.6 commit 5 — interior pkg respawn. Mirrors the ring
  // pattern: picked entries tick down respawnIn; at 0 the cell re-
  // rolls a fresh pkg (with current terrainOrigin) so interior
  // doesn't become a picked-clean wasteland.
  const table = S.interiorPkgs || {};
  for (const key of Object.keys(table)) {
    const entry = table[key];
    if (!entry || !entry.picked || entry.respawnIn <= 0) continue;
    entry.respawnIn--;
    if (entry.respawnIn === 0) {
      entry.pkg = rollInteriorPkg(entry.terrainOrigin, entry.x, entry.y);
      entry.picked = false;
    }
  }
}
