/* ==============================================
   THE LONG HAUL — package pickup + delivery + respawn

   Three functions moved from main.js:
     scanForPickup()     — proximity pickup scan (runs every
                           walking/carrying tick). Also handles
                           sandalweed harvest.
     tryDeliver(nodeId)  — fires on node arrival. Most cross-
                           system function in the codebase —
                           touches recovery, multiplayer, trust,
                           identification, render, and log.
     tickPkgRespawns()   — periodic (every 10 ticks) rescan
                           that un-picks packages whose
                           respawnIn has counted to zero.

   Package lifecycle:
     - Generated by world.js at startup (one pkg per eligible cell).
     - Picked up here → pkg.picked=true, copied into S.inventory
       with _worldCell backref.
     - Delivered here → normal pkgs get respawnIn=PKG_RESPAWN_TICKS;
       recovery pkgs one-shot (cell.pkg=null).

   Recovery metadata (isRecovery, recoveryFromPorter) rides the
   package from pickup → inventory → delivery; delivery broadcasts
   lost_recovered via postActivity.
   ============================================== */
'use strict';

import { S } from './state.js';
import * as C from './constants.js';
import { NPC_DEFS } from './data/npc-defs.js';
import { postActivity, shortPorterId } from './multiplayer.js';
import { updatePorterStripBadges } from './recovery.js';
import { addTrust } from './trust.js';
import { getNodeStage, setNodeStage } from './identification.js';
import { sandalCap, renderBoots } from './boots.js';
import { addLog } from './render/log.js';
import { renderCourierStack, renderCargoSlots } from './render/hud.js';
import { drawRouteMap } from './render/route-map.js';
import { renderSettlements } from './render/settlements.js';

// Local aliases — live references into S._transient. Never reassign these.
const els = S._transient.els;
const worldCells = S._transient.worldCells;

// v0.0.7.21 — sticky gun occupies one cargo slot unless holstered.
// Every pkg slot accounting goes through this helper so cargo
// cap math stays in one place. renderCargoSlots also reads this
// to paint the right slot count.
export function effectiveMaxSlots() {
  if (S.stickyGun && !S.stickyGun.holstered) return Math.max(0, S.maxSlots - 1);
  return S.maxSlots;
}

// v0.0.7.21 — effective pickup range. Base C.PKG_PICKUP_RANGE when
// bare-handed; extended to C.STICKY_GUN_RANGE when gun is owned and
// has ammo. Holstering does NOT extend range — you can't shoot
// through the holster.
function pickupRange() {
  if (S.stickyGun && !S.stickyGun.holstered && S.stickyGun.ammo > 0) {
    return C.STICKY_GUN_RANGE;
  }
  return C.PKG_PICKUP_RANGE;
}

// ============================================================
// PACKAGE PICKUP
// ============================================================
export function scanForPickup() {
  if (S.status !== 'walking' && S.status !== 'carrying') return;
  const courierCell = Math.floor((S.edgeIdx * C.CELLS_PER_EDGE) + (S.dotT * C.CELLS_PER_EDGE));
  const range = pickupRange();
  for (let offset = 0; offset <= range; offset++) {
    const ci   = (courierCell + offset) % C.TOTAL_CELLS;
    const cell = worldCells[ci];
    if (!cell) continue;

    if (cell.sandal) {
      if (S.sandalweedCount >= sandalCap()) continue;
      cell.sandal = false;
      cell.html = `<span class="fc fc-fl">   </span>`;
      S.sandalweedCount++;
      addLog(`harvested <span class="log-hi">sandalweed</span> (${S.sandalweedCount}/${sandalCap()})`);
      renderBoots();
      continue;
    }

    if (!cell.pkg || cell.pkg.picked) continue;
    const pkg = cell.pkg;
    // v0.0.7.19 commit 2b — pickup-fail log lines. Dedupe by
    // (ci:usedSlots:usedWeight) so we don't spam the log each tick
    // while walking past a too-heavy pkg, but DO re-fire after the
    // player drops or delivers cargo and walks past again.
    // v0.0.7.21 — slot capacity now goes through effectiveMaxSlots()
    // so the sticky gun occupying a slot is accounted for.
    const slotsShort  = pkg.slots > effectiveMaxSlots() - S.usedSlots;
    const weightShort = pkg.kg    > S.maxWeight - S.usedWeight;
    if (slotsShort || weightShort) {
      const key = `${ci}:${S.usedSlots}:${S.usedWeight}`;
      if (S._transient.lastPickupFailKey !== key) {
        S._transient.lastPickupFailKey = key;
        const reason = slotsShort ? 'no cargo slots' : 'too heavy';
        addLog(`<span class="log-wn">can't lift</span> [${pkg.size}] ${pkg.label} \u2014 ${reason}`);
      }
      continue;
    }

    pkg.picked = true;
    // v0.0.7.21 — sticky gun ammo decrement. Only on cross-range picks:
    // if offset > C.PKG_PICKUP_RANGE, the gun reached past bare-hand range
    // and a shot was spent. Offsets within bare-hand range don't consume
    // ammo (courier just walked up to it).
    if (S.stickyGun && !S.stickyGun.holstered && offset > C.PKG_PICKUP_RANGE && S.stickyGun.ammo > 0) {
      S.stickyGun.ammo--;
    }
    const carried = {
      size: pkg.size, label: pkg.label, kg: pkg.kg, slots: pkg.slots,
      scrip: pkg.scrip, isLost: pkg.isLost, destId: pkg.destId,
      isRecovery: !!pkg.isRecovery,
      recoveryFromPorter: pkg.recoveryFromPorter || null,
      _worldCell: ci,
    };
    S.inventory.push(carried);
    S.usedSlots  += carried.slots;
    S.usedWeight += carried.kg;
    S.status = 'carrying';
    renderCourierStack();
    renderCargoSlots(true);
    if (els.courierAt) els.courierAt.className = 'tlh-at bounce carry';
    const lostTag = carried.isRecovery
      ? ` <span class="log-wn">[recovery]</span> from <span class="log-hi">${shortPorterId(carried.recoveryFromPorter)}</span>`
      : (carried.isLost ? ' <span class="log-wn">[lost pkg]</span>' : '');
    addLog(`picked up <span class="log-hi">[${carried.size}] ${carried.label}</span>${lostTag}`);
    return;
  }
}

// ============================================================
// PACKAGE DELIVERY
// ============================================================
export function tryDeliver(arrivedNodeId) {
  // v0.0.7.21 — sticky gun ammo refill at H, regardless of whether
  // there's a pkg to deliver. Home = rearm station.
  if (arrivedNodeId === 'H' && S.stickyGun && S.stickyGun.ammo < S.stickyGun.ammoMax) {
    const refilled = S.stickyGun.ammoMax - S.stickyGun.ammo;
    S.stickyGun.ammo = S.stickyGun.ammoMax;
    addLog(`<span class="log-ok">sticky gun</span> refilled \u2014 +${refilled} shots`);
  }

  const toDeliver = S.inventory.filter(p => p.destId === arrivedNodeId);
  if (toDeliver.length === 0) return;
  const settle = S.settlements[arrivedNodeId];
  const destLabel = settle ? settle.label : arrivedNodeId;
  toDeliver.forEach(pkg => {
    S.scrip      += pkg.scrip;
    S.delivered  += 1;
    S.usedSlots  -= pkg.slots;
    S.usedWeight -= pkg.kg;
    S.inventory.splice(S.inventory.indexOf(pkg), 1);
    if (pkg._worldCell !== undefined && worldCells[pkg._worldCell] && worldCells[pkg._worldCell].pkg) {
      if (pkg.isRecovery) {
        worldCells[pkg._worldCell].pkg = null;
        worldCells[pkg._worldCell].isRecovery = false;
        S.activeRecoveryCount = Math.max(0, S.activeRecoveryCount - 1);
        updatePorterStripBadges();
      } else {
        worldCells[pkg._worldCell].pkg.respawnIn = C.PKG_RESPAWN_TICKS;
      }
    }
    if (settle) { settle.supply = Math.min(100, settle.supply + 3); settle.rebuild = Math.min(100, settle.rebuild + 1); }
    const node = S.routeNodes.find(n => n.id === arrivedNodeId);
    if (node && getNodeStage(arrivedNodeId) < 3) {
      setNodeStage(arrivedNodeId, 3);
      addLog(`discovered: <span class="log-hi">${node.label}</span>`);
      drawRouteMap();
      renderSettlements();
      postActivity('discovery', { nodeId: arrivedNodeId, label: node.label });
      if (NPC_DEFS[arrivedNodeId]) {
        addTrust(arrivedNodeId, C.TRUST_GAIN_DISCOVERY, 'discovery');
      }
    }
    addLog(`delivered to <span class="log-hi">${destLabel}</span> \u2014 <span class="log-ok">+${pkg.scrip}\u00a2</span>`);
    postActivity('delivery', { destId: arrivedNodeId, destLabel, scrip: pkg.scrip, size: pkg.size });

    if (pkg.isRecovery && pkg.recoveryFromPorter) {
      postActivity('lost_recovered', {
        label: pkg.label,
        size: pkg.size,
        forPorter: pkg.recoveryFromPorter,
      });
      addLog(`<span class="log-ok">recovered</span> <span class="log-hi">${pkg.label}</span> \u2014 left by <span class="log-hi">${shortPorterId(pkg.recoveryFromPorter)}</span>`);
    }

    if (NPC_DEFS[arrivedNodeId]) {
      const gain = pkg.isLost ? C.TRUST_GAIN_LOST_DELIVERY : C.TRUST_GAIN_DELIVERY;
      addTrust(arrivedNodeId, gain, pkg.isLost ? 'lost-delivery' : 'delivery');
    }
  });
  renderCourierStack();
  renderCargoSlots(true);
  if (S.inventory.length === 0) {
    S.status = 'walking';
    if (els.courierAt) els.courierAt.className = 'tlh-at bounce';
  }
  renderSettlements();
}

export function tickPkgRespawns() {
  for (let i = 0; i < C.TOTAL_CELLS; i++) {
    const cell = worldCells[i];
    if (!cell || !cell.pkg || !cell.pkg.picked || cell.pkg.respawnIn <= 0) continue;
    cell.pkg.respawnIn--;
    if (cell.pkg.respawnIn === 0) {
      const active = worldCells.filter(c => c.edgeIdx === cell.edgeIdx && c.pkg && !c.pkg.picked).length;
      if (active < C.PKG_MAX_PER_EDGE) {
        cell.pkg.picked = false;
        addLog(`<span class="log-ok">new package</span> spotted on the road`);
      } else {
        cell.pkg.respawnIn = C.PKG_RESPAWN_TICKS;
      }
    }
  }
}
